name: corso_games_app
description: A collection of flutter games. Good luck, have fun.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+18

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  bloc: ^8.1.2
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.2
  csv: ^6.0.0
  device_info_plus: ^10.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  expansion_tile_card: ^3.0.0
  file_picker: ^8.0.3
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.3.2
  flutter_neumorphic: 
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  flutter_pw_validator: ^1.6.0
  font_awesome_flutter: ^10.3.0
  go_router: ^14.0.2
  hydrated_bloc: ^9.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  permission_handler: ^10.2.0
  provider: ^6.0.2
  share_plus: ^9.0.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/main/cg-1.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/main/cg-1.png"
    background_color: "#FFFFF8"
    theme_color: "#FFFFF8"
  windows:
    generate: true
    image_path: "assets/images/main/cg-1.png"
    icon_size: 48 

flutter:
  uses-material-design: true

  assets:
    - assets/data/el_word/
    - assets/data/honeygram/
    - assets/fonts/slide_to_slide/
    - assets/images/dino_dash/
    - assets/images/dino_dash/cacti/
    - assets/images/dino_dash/dino/
    - assets/images/dino_dash/ptera/
    - assets/images/main/
    - assets/images/minesweeper/
    - assets/images/slide_to_slide/
    - assets/images/solitare/
    - assets/images/tappy_bird/

  fonts:
    - family: Plaster
      fonts:
        - asset: assets/fonts/slide_to_slide/Plaster-Regular.ttf