// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBucVKBYnzsiwOZndh9AjrhrdgkT-xi_uI',
    appId: '1:381305383797:web:2c6b76220fef9780ba013c',
    messagingSenderId: '381305383797',
    projectId: 'corso-games',
    authDomain: 'corso-games.firebaseapp.com',
    storageBucket: 'corso-games.appspot.com',
    measurementId: 'G-SY2YCZP017',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qRxb7X8rm6GNeUUSKr77e2JlxdNR6PQ',
    appId: '1:381305383797:android:0888ac66068465a4ba013c',
    messagingSenderId: '381305383797',
    projectId: 'corso-games',
    storageBucket: 'corso-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcio1_J93Vx7gjB5uKrxKVstnTRwUJoik',
    appId: '1:381305383797:ios:ea2171690cdc0c4bba013c',
    messagingSenderId: '381305383797',
    projectId: 'corso-games',
    storageBucket: 'corso-games.appspot.com',
    iosClientId: '381305383797-0ovhjbk3eveq1vb6od80plmt2h2plj1n.apps.googleusercontent.com',
    iosBundleId: 'com.dtfun.corsoGamesApp',
  );
}
